baseURL = "https://chanel.cdox.ltd/"
languageCode = "en-us"
title = "Canned Ox Visuals"

Paginate = 5

ignoreFiles = [ ".*/static/js/react-hugo/node_modules/.*" ]

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  image = "/projects/lauren-towel/images-right/099A8049.jpg"