[functions]
  directory = "functions"

[build.environment]
  GO_IMPORT_PATH="github.com/rwboyer/dino-don-inc-11ty"
  GO_VERSION="1.17"

[[redirects]]
  from = "/jws/*"
  to = "https://mccrery.cdox.cc/jws/:splat"
  status = 200
  force = true
  signed = "IMPOSSIBLE"
  conditions = {Role = ["admin"]}